[project]
name = "creative-agent"
version = "0.1.0"
description = "基于LangGraph的创意代理工作流"
readme = "README.md"
requires-python = ">=3.11"
authors = [{ name = "Jarrett" }]
dependencies = ["langgraph", "langchain-openai", "python-dotenv", "langgraph-cli[inmem]"]